package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Candidateans generated by hbm2java
 */
public class Candidateans implements java.io.Serializable {

	private Integer caid;
	private Candidate candidate;
	private String questionno;
	private String ans;

	public Candidateans() {
	}

	public Candidateans(Candidate candidate, String questionno, String ans) {
		this.candidate = candidate;
		this.questionno = questionno;
		this.ans = ans;
	}

	public Integer getCaid() {
		return this.caid;
	}

	public void setCaid(Integer caid) {
		this.caid = caid;
	}

	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	public String getQuestionno() {
		return this.questionno;
	}

	public void setQuestionno(String questionno) {
		this.questionno = questionno;
	}

	public String getAns() {
		return this.ans;
	}

	public void setAns(String ans) {
		this.ans = ans;
	}

}
