package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Candidate generated by hbm2java
 */
public class Candidate implements java.io.Serializable {

	private Integer cid;
	private Student student;
	private Testseries testseries;
	private String date;
	private String time;
	private String standard;
	private Set scores = new HashSet(0);
	private Set candidateanses = new HashSet(0);

	public Candidate() {
	}

	public Candidate(Student student, Testseries testseries, String date, String time, String standard, Set scores,
			Set candidateanses) {
		this.student = student;
		this.testseries = testseries;
		this.date = date;
		this.time = time;
		this.standard = standard;
		this.scores = scores;
		this.candidateanses = candidateanses;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Testseries getTestseries() {
		return this.testseries;
	}

	public void setTestseries(Testseries testseries) {
		this.testseries = testseries;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	public Set getScores() {
		return this.scores;
	}

	public void setScores(Set scores) {
		this.scores = scores;
	}

	public Set getCandidateanses() {
		return this.candidateanses;
	}

	public void setCandidateanses(Set candidateanses) {
		this.candidateanses = candidateanses;
	}

}
