package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Exampaper generated by hbm2java
 */
public class Exampaper implements java.io.Serializable {

	private Integer eid;
	private Testseries testseries;
	private String std;
	private String questionno;
	private String question;
	private String ch1;
	private String ch2;
	private String ch3;
	private String ch4;
	private String ch5;
	private String ans;
	private String questionmarks;

	public Exampaper() {
	}

	public Exampaper(Testseries testseries, String std, String questionno, String question, String ch1, String ch2,
			String ch3, String ch4, String ch5, String ans, String questionmarks) {
		this.testseries = testseries;
		this.std = std;
		this.questionno = questionno;
		this.question = question;
		this.ch1 = ch1;
		this.ch2 = ch2;
		this.ch3 = ch3;
		this.ch4 = ch4;
		this.ch5 = ch5;
		this.ans = ans;
		this.questionmarks = questionmarks;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Testseries getTestseries() {
		return this.testseries;
	}

	public void setTestseries(Testseries testseries) {
		this.testseries = testseries;
	}

	public String getStd() {
		return this.std;
	}

	public void setStd(String std) {
		this.std = std;
	}

	public String getQuestionno() {
		return this.questionno;
	}

	public void setQuestionno(String questionno) {
		this.questionno = questionno;
	}

	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getCh1() {
		return this.ch1;
	}

	public void setCh1(String ch1) {
		this.ch1 = ch1;
	}

	public String getCh2() {
		return this.ch2;
	}

	public void setCh2(String ch2) {
		this.ch2 = ch2;
	}

	public String getCh3() {
		return this.ch3;
	}

	public void setCh3(String ch3) {
		this.ch3 = ch3;
	}

	public String getCh4() {
		return this.ch4;
	}

	public void setCh4(String ch4) {
		this.ch4 = ch4;
	}

	public String getCh5() {
		return this.ch5;
	}

	public void setCh5(String ch5) {
		this.ch5 = ch5;
	}

	public String getAns() {
		return this.ans;
	}

	public void setAns(String ans) {
		this.ans = ans;
	}

	public String getQuestionmarks() {
		return this.questionmarks;
	}

	public void setQuestionmarks(String questionmarks) {
		this.questionmarks = questionmarks;
	}

}
