package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Score generated by hbm2java
 */
public class Score implements java.io.Serializable {

	private Integer sid;
	private Candidate candidate;
	private Testseries testseries;
	private String score;

	public Score() {
	}

	public Score(Candidate candidate, Testseries testseries, String score) {
		this.candidate = candidate;
		this.testseries = testseries;
		this.score = score;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public Candidate getCandidate() {
		return this.candidate;
	}

	public void setCandidate(Candidate candidate) {
		this.candidate = candidate;
	}

	public Testseries getTestseries() {
		return this.testseries;
	}

	public void setTestseries(Testseries testseries) {
		this.testseries = testseries;
	}

	public String getScore() {
		return this.score;
	}

	public void setScore(String score) {
		this.score = score;
	}

}
