package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer sid;
	private String name;
	private String uniqueid;
	private String logname;
	private String logpass;
	private String standard;
	private String division;
	private String stdrollno;
	private Integer pid;
	private String address;
	private String age;
	private String dob;
	private String gender;
	private String aadhar;
	private Integer fsid;
	private String deductionfee;
	private String unpaid;
	private String paid;
	private String fine;
	private String totalfee;
	private String deposit;
	private String birthcertificate;
	private String email;
	private Set candidates = new HashSet(0);

	public Student() {
	}

	public Student(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public Student(String name, String uniqueid, String logname, String logpass, String standard, String division,
			String stdrollno, Integer pid, String address, String age, String dob, String gender, String aadhar,
			Integer fsid, String deductionfee, String unpaid, String paid, String fine, String totalfee,
			String deposit, String birthcertificate, String email, Set candidates) {
		this.name = name;
		this.uniqueid = uniqueid;
		this.logname = logname;
		this.logpass = logpass;
		this.standard = standard;
		this.division = division;
		this.stdrollno = stdrollno;
		this.pid = pid;
		this.address = address;
		this.age = age;
		this.dob = dob;
		this.gender = gender;
		this.aadhar = aadhar;
		this.fsid = fsid;
		this.deductionfee = deductionfee;
		this.unpaid = unpaid;
		this.paid = paid;
		this.fine = fine;
		this.totalfee = totalfee;
		this.deposit = deposit;
		this.birthcertificate = birthcertificate;
		this.email = email;
		this.candidates = candidates;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUniqueid() {
		return this.uniqueid;
	}

	public void setUniqueid(String uniqueid) {
		this.uniqueid = uniqueid;
	}

	public String getLogname() {
		return this.logname;
	}

	public void setLogname(String logname) {
		this.logname = logname;
	}

	public String getLogpass() {
		return this.logpass;
	}

	public void setLogpass(String logpass) {
		this.logpass = logpass;
	}

	public String getStandard() {
		return this.standard;
	}

	public void setStandard(String standard) {
		this.standard = standard;
	}

	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	public String getStdrollno() {
		return this.stdrollno;
	}

	public void setStdrollno(String stdrollno) {
		this.stdrollno = stdrollno;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAadhar() {
		return this.aadhar;
	}

	public void setAadhar(String aadhar) {
		this.aadhar = aadhar;
	}

	public Integer getFsid() {
		return this.fsid;
	}

	public void setFsid(Integer fsid) {
		this.fsid = fsid;
	}

	public String getDeductionfee() {
		return this.deductionfee;
	}

	public void setDeductionfee(String deductionfee) {
		this.deductionfee = deductionfee;
	}

	public String getUnpaid() {
		return this.unpaid;
	}

	public void setUnpaid(String unpaid) {
		this.unpaid = unpaid;
	}

	public String getPaid() {
		return this.paid;
	}

	public void setPaid(String paid) {
		this.paid = paid;
	}

	public String getFine() {
		return this.fine;
	}

	public void setFine(String fine) {
		this.fine = fine;
	}

	public String getTotalfee() {
		return this.totalfee;
	}

	public void setTotalfee(String totalfee) {
		this.totalfee = totalfee;
	}

	public String getDeposit() {
		return this.deposit;
	}

	public void setDeposit(String deposit) {
		this.deposit = deposit;
	}

	public String getBirthcertificate() {
		return this.birthcertificate;
	}

	public void setBirthcertificate(String birthcertificate) {
		this.birthcertificate = birthcertificate;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set candidates) {
		this.candidates = candidates;
	}

}
