package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer tid;
	private String name;
	private String post;
	private String logname;
	private String logpass;
	private String salary;
	private String photo;
	private String aadhar;
	private String pancade;
	private String gender;
	private String age;
	private String dob;
	private String email;
	private String joindate;
	private String subjects;

	public Teacher() {
	}

	public Teacher(String name, String post, String logname, String logpass, String salary, String photo,
			String aadhar, String pancade, String gender, String age, String dob, String email, String joindate,
			String subjects) {
		this.name = name;
		this.post = post;
		this.logname = logname;
		this.logpass = logpass;
		this.salary = salary;
		this.photo = photo;
		this.aadhar = aadhar;
		this.pancade = pancade;
		this.gender = gender;
		this.age = age;
		this.dob = dob;
		this.email = email;
		this.joindate = joindate;
		this.subjects = subjects;
	}

	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public String getLogname() {
		return this.logname;
	}

	public void setLogname(String logname) {
		this.logname = logname;
	}

	public String getLogpass() {
		return this.logpass;
	}

	public void setLogpass(String logpass) {
		this.logpass = logpass;
	}

	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getAadhar() {
		return this.aadhar;
	}

	public void setAadhar(String aadhar) {
		this.aadhar = aadhar;
	}

	public String getPancade() {
		return this.pancade;
	}

	public void setPancade(String pancade) {
		this.pancade = pancade;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getJoindate() {
		return this.joindate;
	}

	public void setJoindate(String joindate) {
		this.joindate = joindate;
	}

	public String getSubjects() {
		return this.subjects;
	}

	public void setSubjects(String subjects) {
		this.subjects = subjects;
	}

}
