package com.pojo;

// Generated Jan 15, 2021 2:45:45 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Testseries generated by hbm2java
 */
public class Testseries implements java.io.Serializable {

	private Integer tsid;
	private String tsname;
	private Set exampapers = new HashSet(0);
	private Set candidates = new HashSet(0);
	private Set scores = new HashSet(0);

	public Testseries() {
	}

	public Testseries(String tsname, Set exampapers, Set candidates, Set scores) {
		this.tsname = tsname;
		this.exampapers = exampapers;
		this.candidates = candidates;
		this.scores = scores;
	}

	public Integer getTsid() {
		return this.tsid;
	}

	public void setTsid(Integer tsid) {
		this.tsid = tsid;
	}

	public String getTsname() {
		return this.tsname;
	}

	public void setTsname(String tsname) {
		this.tsname = tsname;
	}

	public Set getExampapers() {
		return this.exampapers;
	}

	public void setExampapers(Set exampapers) {
		this.exampapers = exampapers;
	}

	public Set getCandidates() {
		return this.candidates;
	}

	public void setCandidates(Set candidates) {
		this.candidates = candidates;
	}

	public Set getScores() {
		return this.scores;
	}

	public void setScores(Set scores) {
		this.scores = scores;
	}

}
